apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "worker.fullname" . }}-configmap
  labels:
    {{- include "worker.labels" . | nindent 4 }}
data:
  workers_ini: |
    [global]
    HOST = {{ .Values.openqa.host }}
    BACKEND = qemu
    {{ if .Values.workerClass -}}
    WORKER_CLASS = {{ .Values.workerClass }}
    {{ end -}}
    {{ if .Values.cacheService -}}
    CACHEDIRECTORY = /var/lib/openqa/cache
    CACHELIMIT = {{ .Values.cacheLimit }}
    CACHEWORKERS = 1

    [{{ .Values.openqa.host }}]
    #TESTPOOLSERVER = rsync://{{ .Values.openqa.host }}/tests
    TESTPOOLSERVER = rsync://3.23.132.38/tests
    {{ end }}
  client_conf: |
    [{{ .Values.openqa.host }}]
    key = {{ .Values.openqa.key }}
    secret = {{ .Values.openqa.secret }}
  resolvconf: |
    nameserver 1.1.1.1
    search openqa.svc.cluster.openqa.k8s-extarch.kpou2.rockylinux.org svc.cluster.local
    options ndots:7
